### ISSUE TITLE
There are quite a few mistakes

### ISSUE THREAD

**Issue by iMarlboro** [digimakergo/dmdemo#1]
1. web/admin
- npm start has some errors, such as "You may need an additional loader to handle the results of these loaders", "SyntaxError: /node_modules/react-sortablejs/dist/index.js: Missing class properties transform."
```
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
```
```
SyntaxError: /web/admin/node_modules/react-sortablejs/dist/index.js: Missing class properties transform.
  158 | };
  159 | class $7fe8e3ea572bda7a$export$11bbed9ee0012c13 extends (0, $8zHUo$react.Component) {
> 160 |     /* eslint-disable-next-line */ static defaultProps = {
      |                                    ^
  161 |         clone: (item)=>item
  162 |     };
  163 |     constructor(props){
```

balabala.....

These are small fixable problems, but they affect the experience

**Comment by xc** [comment]
Thanks. We are in the process of reflecting the whole admin. Soon we will have a new version.

**Comment by xc** [comment]
Hi, we have updated the digimaker-ui and this one should be solved.

PS. you may need to use npm install --legacy-peer-deps if your npm version is higher than 7.
